# serverless.yml

service: aws-serverless-express-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: /
          method: get
